apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest
spec:
  selector:
    matchLabels:
      app: webtest
  replicas: 1
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
      - name: webtest
        image: registry.techgentsia.com/admin-meet:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: my-secret
