apiVersion: v1
kind: Service
metadata:
  name: webtest-service
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30090
  selector:
    app: webtest 
  externalIPs: [192.168.7.138]
